import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import TanstackProvider from "@/provider/tanstack-provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "@szhsin/react-menu/dist/index.css";
import "@szhsin/react-menu/dist/transitions/slide.css";
import "./globals.css";

import { UserContextProvider } from "@/context/user-context";
import NextTopLoader from "nextjs-toploader";

const outfit = Outfit({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Toplorgical - Cooperative",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <ToastContainer />
        <NextTopLoader color="#4f46e5" />
        <UserContextProvider>
          <TanstackProvider>{children}</TanstackProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
